Note.destroy_all
User.destroy_all
Planet.destroy_all

demo = User.create( username: "fguido", password: "1234")

puts "Creating planets"

planet1 = Planet.create(name: "Mercury", about: "Mercury is the smallest planet in the Solar System and the closest to the Sun. Its orbit around the Sun takes 87.97 Earth days, the shortest of all the Sun's planets.", info: "From the surface of Mercury, the Sun would appear more than three times as large as it does when viewed from Earth, and the sunlight would be as much as seven times brighter. Despite its proximity to the Sun, Mercury is not the hottest planet in our solar system that title belongs to nearby Venus, thanks to its dense atmosphere.", fact: "Because Mercury is so close to the Sun, it is hard to directly observe from Earth except during dawn or twilight when the Sun's brightness doesn't outshine little Mercury. However, 13 times each century, observers on Earth can watch Mercury pass across the face of the Sun, an event called a transit. These rare transits fall within several days of May 8 and November 10. Previous transits occurred May 7, 2003, Nov. 8, 2006, and May 9, 2016, and Nov. 11, 2019.", image: "https://solarsystem.nasa.gov/system/stellar_items/list_view_images/2_mercury_480x320_new.jpg", imagetwo: "https://solarsystem.nasa.gov/system/resources/list_images/1053_merc_320.png", imagethree: "https://solarsystem.nasa.gov/system/resources/list_images/769_PIA16820_thumb.jpg", imagefour: "https://solarsystem.nasa.gov/system/resources/list_images/522_PIA19423_320.jpg")
planet2 = Planet.create(name: "Venus", about: "Venus is the second planet from the Sun and is named after the Roman goddess of love and beauty. As the brightest natural object in Earth's night sky after the Moon, Venus can cast shadows and can be visible to the naked eye in broad daylight.", info: "Venus is the second planet from the Sun and is Earths closest planetary neighbor. Its one of the four inner, terrestrial (or rocky) planets, and its often called Earths twin because its similar in size and density. These are not identical twins, however there are radical differences between the two worlds. Another big difference from Earth, Venus rotates on its axis backward, compared to most of the other planets in the solar system. This means that, on Venus, the Sun rises in the west and sets in the east, opposite to what we experience on Earth.", fact: "Venus has a thick, toxic atmosphere filled with carbon dioxide and its perpetually shrouded in thick, yellowish clouds of sulfuric acid that trap heat, causing a runaway greenhouse effect. Its the hottest planet in our solar system, even though Mercury is closer to the Sun. Surface temperatures on Venus are about 900 degrees Fahrenheit (475 degrees Celsius)", image: "https://solarsystem.nasa.gov/system/stellar_items/list_view_images/3_480x320_venus.png", imagetwo: "https://solarsystem.nasa.gov/system/resources/list_images/574_PIA00486Thumbnail.jpg", imagethree: "https://solarsystem.nasa.gov/system/resources/list_images/547_PIA00479_320.jpg", imagefour: "https://solarsystem.nasa.gov/system/resources/list_images/546_PIA00480_320.jpg")
planet3 = Planet.create(name: "Earth", about: "Earth is the third planet from the Sun and the only astronomical object known to harbor life. While large amounts of water can be found throughout the Solar System, only Earth sustains liquid surface water.", info: "While Earth is only the fifth largest planet in the solar system, it is the only world in our solar system with liquid water on the surface. Just slightly larger than nearby Venus, Earth is the biggest of the four planets closest to the Sun, all of which are made of rock and metal.", fact: "The name Earth is at least 1,000 years old. All of the planets, except for Earth, were named after Greek and Roman gods and goddesses. However, the name Earth is a Germanic word, which simply means “the ground.”", image: "https://solarsystem.nasa.gov/system/stellar_items/list_view_images/4_earth_480x320.jpg", imagetwo: "https://solarsystem.nasa.gov/system/resources/list_images/2337_as11-44-6549_320.jpg", imagethree: "https://solarsystem.nasa.gov/system/resources/list_images/851_JSC2016E096363_thumb.jpg", imagefour: "https://solarsystem.nasa.gov/system/resources/list_images/819_khurdopin_oli_2017133_lrg_thumb.jpg")
planet4 = Planet.create(name: "Mars", about: "Mars is the fourth planet from the Sun and the second-smallest planet in the Solar System, being larger than only Mercury. In English, Mars carries the name of the Roman god of war and is often called the Red Planet.", info: "Mars is one of the most explored bodies in our solar system, and it's the only planet where we've sent rovers to roam the alien landscape. NASA currently has two rovers (Curiosity and Perseverance), one lander (InSight), and one helicopter (Ingenuity) exploring the surface of Mars.", fact: "One day on Mars takes a little over 24 hours. Mars makes a complete orbit around the Sun (a year in Martian time) in 687 Earth days.", image: "https://solarsystem.nasa.gov/system/stellar_items/list_view_images/6_mars_480x320.jpg", imagetwo: "https://solarsystem.nasa.gov/system/resources/list_images/2511_ESP_062839_1740_320.jpg", imagethree: "https://solarsystem.nasa.gov/system/resources/list_images/2431_PIA07997_320.jpg", imagefour: "https://solarsystem.nasa.gov/system/resources/list_images/2429_PIA00567_320.jpg")
planet5 = Planet.create(name: "Jupiter", about: "Jupiter is the fifth planet from the Sun and the largest in the Solar System. It is a gas giant with a mass more than two and a half times that of all the other planets in the Solar System combined, but slightly less than one-thousandth the mass of the Sun.", info: "Jupiter's familiar stripes and swirls are actually cold, windy clouds of ammonia and water, floating in an atmosphere of hydrogen and helium. Jupiters iconic Great Red Spot is a giant storm bigger than Earth that has raged for hundreds of years.", fact: "Fifth in line from the Sun, Jupiter is, by far, the largest planet in the solar system more than twice as massive as all the other planets combined.", image: "https://solarsystem.nasa.gov/system/stellar_items/list_view_images/9_jupiter_480x320_new.jpg", imagetwo: "https://solarsystem.nasa.gov/system/resources/list_images/2479_grs_animation_320.png", imagethree: "https://solarsystem.nasa.gov/system/resources/list_images/427_JunoClosesInOnJupiterThumbnail.jpg", imagefour: "https://solarsystem.nasa.gov/system/resources/list_images/736_PIA22335-16_320x240.jpg")
planet6 = Planet.create(name: "Saturn", about: "Saturn is the sixth planet from the Sun and the second-largest in the Solar System, after Jupiter. It is a gas giant with an average radius of about nine and a half times that of Earth.", info: "Adorned with thousands of beautiful ringlets, Saturn is unique among the planets. It is not the only planet to have rings made of chunks of ice and rock but none are as spectacular or as complicated as Saturn's.", fact: "Like fellow gas giant Jupiter, Saturn is a massive ball made mostly of hydrogen and helium.", image: "https://solarsystem.nasa.gov/system/feature_items/images/154_saturn_carousel_4.jpg", imagetwo: "https://solarsystem.nasa.gov/system/resources/list_images/17849_PIA14943-320x240.jpg", imagethree: "https://solarsystem.nasa.gov/system/resources/list_images/659_PIA11214_thumb.jpg", imagefour: "https://solarsystem.nasa.gov/system/resources/list_images/185_PIA17172_Thumbnail.jpg")
planet7 = Planet.create(name: "Uranus", about: "Uranus is the seventh planet from the Sun. Its name is a reference to the Greek god of the sky. It has the third-largest planetary radius and fourth-largest planetary mass in the Solar System.", info: "Uranus has 27 known moons, and they are named after characters from the works of William Shakespeare and Alexander Pope. Uranus has 13 known rings. The inner rings are narrow and dark and the outer rings are brightly colored.", fact: "Uranus takes about 17 hours to rotate once (a Uranian day), and about 84 Earth years to complete an orbit of the Sun (a Uranian year). Like Venus, Uranus rotates east to west. But Uranus is unique in that it rotates on its side.", image: "https://solarsystem.nasa.gov/system/stellar_items/list_view_images/69_uranus_480x320.jpg", imagetwo: "https://solarsystem.nasa.gov/system/resources/list_images/605_PIA17306_thumb.jpg", imagethree: "https://solarsystem.nasa.gov/system/resources/list_images/603_PIA00143_thumb.jpg", imagefour: "https://solarsystem.nasa.gov/system/resources/list_images/445_PIA02963Thumbnail.jpg")
planet8 = Planet.create(name: "Neptune", about: "Neptune is the eighth and farthest-known Solar planet from the Sun. In the Solar System, it is the fourth-largest planet by diameter, the third-most-massive planet, and the densest giant planet.", info: "More than 30 times as far from the Sun as Earth, Neptune is the only planet in our solar system not visible to the naked eye and the first predicted by mathematics before its discovery. In 2011 Neptune completed its first 165-year orbit since its discovery in 1846.", fact: "NASA's Voyager 2 is the only spacecraft to have visited Neptune up close. It flew past in 1989 on its way out of the solar system.", image: "https://solarsystem.nasa.gov/system/stellar_items/list_view_images/90_neptune_480x320.jpg", imagetwo: "https://solarsystem.nasa.gov/system/resources/list_images/936_eso1824a_320.jpg", imagethree: "	https://solarsystem.nasa.gov/system/resources/list_images/842_31101484000_02c1a70913_o_thumb.jpg", imagefour: "https://solarsystem.nasa.gov/system/resources/list_images/607_PIA00058_thumb.jpg")

note1 = Note.create(memo: "Hello", user_id: demo.id, planet_id: planet1.id)

puts "done seeding"